// You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

function findTheDifference(s,t){
    const map = new Map()
    for(let i=0; i<s.length; i++){
        map.set(s[i],(map.get(s[i]) || 0)+1 )
    }
    for(let j=0; j<t.length; j++){
        if(!map.has(t[j]) || map.get(t[j]) === 0){
            return t[j]
        }
        map.set(t[j],map.get(t[j])-1)
    }
}